### ISSUE TITLE
Times spanning over midnight (nonsensical hours provided)

### ISSUE THREAD

**Issue by 23tux** [zendesk/biz#133]
How would one deal with opening hours like 17:00 - 01:00? When I try to configure this, I get an error:

       Biz::Schedule.new do |config|
         config.hours = {
           mon: { "17:00" => "01:00" }
         }
       end
     
     Biz::Error::Configuration:
       nonsensical hours provided
     # /usr/local/bundle/gems/biz-1.8.1/lib/biz/validation.rb:32:in `check'
     # /usr/local/bundle/gems/biz-1.8.1/lib/biz/validation.rb:15:in `block in perform'
     # /usr/local/bundle/gems/biz-1.8.1/lib/biz/validation.rb:15:in `each'
     # /usr/local/bundle/gems/biz-1.8.1/lib/biz/validation.rb:15:in `perform'
     # /usr/local/bundle/gems/biz-1.8.1/lib/biz/validation.rb:7:in `perform'
     # /usr/local/bundle/gems/biz-1.8.1/lib/biz/configuration.rb:13:in `initialize'
     # /usr/local/bundle/gems/biz-1.8.1/lib/biz/schedule.rb:9:in `new'
     # /usr/local/bundle/gems/biz-1.8.1/lib/biz/schedule.rb:9:in `initialize'
     # ./spec/lib/opening_hours/schedule_spec.rb:66:in `new'
     # ./spec/lib/opening_hours/schedule_spec.rb:66:in `block (3 levels) in <top (required)>'

Is this something that is planned? Or can I use some kind of workaround for this use case?

**Comment by craiglittle** [comment]
For time periods that span multiple days, the supported configuration pattern is to split the configuration across those days. In this case, you'd do it the following way:

```ruby
Biz::Schedule.new do |config|
  config.hours = {
    mon: {'17:00' => '24:00'},
    tue: {'00:00' => '01:00'}
  }
end
```
